{{ if .Values.auth0.client.create }}
{{ if and (not .Values.auth0.client.machineToMachineOnly) (not .Values.isInternetFacing) }}
{{ fail "Hi. This configuration makes no sense. Your Auth0 client should be machineToMachineOnly for non-internet-facing applications" }}
{{ end }}
{{- include "validate-configuration" $ }}
{{- $configuration := index .Values.configurations .Values.configuration -}}
{{ $createLocalhostCallbacks := false }}
{{ if or (hasSuffix "-staging" .Values.environment) (hasSuffix "-devops-testing" .Values.environment) }}
{{ $createLocalhostCallbacks = true }}
{{ end }}
{{ $shouldAbandon := false }}
{{ if eq .Values.configuration "production" }}
{{ $shouldAbandon = true }}
{{ end }}
apiVersion: auth0.getg5.com.getg5.com/v1
kind: Auth0Client
metadata:
  name: {{ .Release.Name }}
  labels:
    {{ include "helm-labels" . | nindent 4 }}
  annotations:
    {{ if $shouldAbandon }}
    g5devops-operator.getg5.com/abandon-resources: "true"
    {{ end }}
spec:
  {{ with .Values.auth0.client.friendlyName }}
  friendlyName: {{ . | quote }}
  {{ end }}
  {{ if .Values.auth0.client.machineToMachineOnly }}
  appType: non_interactive
  {{ else }}
  appType: regular_web
  {{ end }}
  {{ if not .Values.auth0.client.machineToMachineOnly }}
  connections:
    - "okta"
    {{ if .Values.auth0.client.allowsCustomerLogin }}
    - "Username-Password-Authentication"
    {{ end }}
    {{ if .Values.auth0.client.allowUnifiedLogin}}
    - "unified-login"
    {{ end }}
  {{ end }}
  {{ if .Values.isInternetFacing }}
  callbacks:
    - https://{{ include "publicHostname" . }}/users/auth/auth0/callback
    {{ if $createLocalhostCallbacks }}
    {{ range .Values.auth0.client.localhostPorts }}
    - http://localhost:{{ . }}/users/auth/auth0/callback
    {{ end }}
    {{ end }}
  allowedLogoutURLs:
    - https://{{ include "publicHostname" . }}
    {{ if .Values.auth0.client.allowUnifiedLogin}}
    {{ range .Values.auth0.client.otherLogOutUrls }}
    - {{ . }}
    {{ end }}
    {{ end }}
    {{ if $createLocalhostCallbacks }}
    {{ range .Values.auth0.client.localhostPorts }}
    - http://localhost:{{ . }}
    {{ end }}
    {{ end }}
  {{ end }}
  cookieSecret:
    generate: true
    length: 64
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-auth0-client
spec:
  backendType: gcpSecretsManager
  data:
    - key: auth0-{{ .Release.Name }}-client-id
      name: client-id
    - key: auth0-{{ .Release.Name }}-client-secret
      name: client-secret
    - key: cookie-secret-{{ .Release.Name }}
      name: cookie-secret
  template:
    metadata:
      annotations:
        reloader.stakater.com/match: "true"
      labels:
        app.kubernetes.io/managed-by: "node-web-service"
{{ end }}
