{{ if .Values.auth0.resourceServer.create }}
{{ $shouldAbandon := false }}
{{ if eq .Values.configuration "production" }}
{{ $shouldAbandon = true }}
{{ end }}
{{ if not (or .Values.auth0.resourceServer.allowedApplications .Values.auth0.resourceServer.scopedApplications ) }}
{{ fail "Hi. This configuration makes no sense. If auth0.resourceServer.create is true, you should have allowedApplications set. There's no point having a resource server that allows no connections." }}
{{ end }}
apiVersion: auth0.getg5.com.getg5.com/v1
kind: Auth0ResourceServer
metadata:
  name: {{ .Release.Name }}
  annotations:
    {{ if $shouldAbandon }}
    g5devops-operator.getg5.com/abandon-resources: "true"
    {{ end }}
spec:
  {{ if .Values.auth0.resourceServer.scopes }}
  scopes:
    {{ range .Values.auth0.resourceServer.scopes }}
    - value: {{ .value | quote }}
      description: {{ .description | quote }}
    {{ end }}
  {{ end }}
  clientGrants:
    {{ range .Values.auth0.resourceServer.allowedApplications }}
    - clientApplicationName: {{ . | quote }}
    {{ end }}
    {{ range .Values.auth0.resourceServer.scopedApplications }}
    - clientApplicationName: {{ .name | quote }}
      scopes:
      {{ range .scopes }}
        - {{ . | quote }}
      {{ end }}
    {{ end }}
{{ end }}
