{{ if .Values.hasIngress }}
{{ $redirectFrontendConfigName := (printf "%s-secure-redirect" .Release.Name) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name | quote }}
  labels:
{{ include "helm-labels" . | indent 4 }}
  annotations:
{{ if .Values.forceSSLRedirect }}
    networking.gke.io/v1beta1.FrontendConfig: {{ $redirectFrontendConfigName | quote }}
{{ end }}
{{ if .Values.hasExternalDns }}
    g5devops.com/external-dns: active
    external-dns.alpha.kubernetes.io/hostname: {{ include "publicHostname" . | quote }}
{{ end }}
spec:
  tls:
    # This Secret comes from an ExternalSecret via the bootstrap process, in
    # the gke-essentials chart. Changing the Secret value will update the load balancer.
    - secretName: custom-ingress-certs
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name | quote }}
            port:
              name: http
---
{{ if .Values.forceSSLRedirect }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ $redirectFrontendConfigName | quote }}
  labels:
{{ include "helm-labels" . | indent 4 }}
spec:
  redirectToHttps:
    enabled: true
{{ end }}
{{ end }}
