{{ range $name, $properties := .Values.topics }}
{{- if $properties.create }}
{{ include "pubsub.topic" (dict "root" $ "name" $name) }}
{{- end }}
---
{{ $publisherArgs := dict "root" $ "topic" $name "gsaName" (include "node-web-service.gsaName" $) }}
{{ if .associatedProject }}
{{ $_ := set $publisherArgs "projectID" (include "cloud-helper.values.associatedProject" (list $ $properties.associatedProject)) }}
{{ end }}
{{ include "pubsub.publisher" $publisherArgs }}
---
{{ end }}
