{{ range $name, $properties := .Values.subscriptions }}
{{ $subscriptionArgs := dict "root" $ "topic" $name "gsaName" (include "node-web-service.gsaName" $) }}
{{ if .associatedProject }}
{{ $_ := set $subscriptionArgs "projectID" (include "cloud-helper.values.associatedProject" (list $ $properties.associatedProject)) }}
{{ end }}
{{ if .subscriptionConfig }}
{{ $_ := set $subscriptionArgs "subscriptionConfig" .subscriptionConfig }}
{{ end }}
{{ include "pubsub.subscription" $subscriptionArgs }}
---
{{ end }}
