apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name | quote }}
  labels:
{{ include "helm-labels" . | indent 4 }}
{{ if not .Values.hasIngress }}
  annotations:
    g5devops.com/external-dns: active
{{- end }}
spec:
  hosts:
    # Match on in-cluster traffic with short hostname
    - {{ .Release.Name | quote }}
    # Match on in-cluster traffic with FQDN
    - "{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local"
{{ if .Values.isInternetFacing -}}
  {{- include "validate-configuration" $ }}
  {{- $configuration := index .Values.configurations .Values.configuration -}}
  {{- $defaultIstioGateway := "istio-system/g5devops" }}
    # configuration was: {{ required "configuration is required" .Values.configuration }}
    # environment was: {{ required "environment is required" .Values.environment }}
  {{- if eq .Values.configuration "production" -}}
    {{- $defaultIstioGateway = "istio-system/g5marketingcloud" -}}
  {{- end }}

    # Match on Internet traffic
    - {{ include "publicHostname" . | quote }}
  gateways:
    - {{ $configuration.istioGateway | default $defaultIstioGateway | quote }}
{{- end }}
  http:
  - route:
    - destination:
        port:
          number: 80
        host: {{ .Release.Name | quote }}
