apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    {{ include "helm-labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/component: web-app
